pipeline {
    agent any
    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "Maven"
        docker "Docker"
    }
    
    stages {
        stage('Clone the repo') {
            steps {
                echo 'Cloning the repository:'
                git url: 'https://github.com/mudit097/node-todo-cicd.git'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Building the ToDo application on Docker'
                sh 'docker build . -t todo-app'
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Deploying the application on Docker'
                sh 'docker run -p 8000:8000 -d todo-app'
            }
        }
    }
}
